config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'events#check'
  get 'availabilities', to: 'events#availabilities'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  def self.availabilities(start_date)
    weekdays = get_week(start_date)
    weekdays.each do |day|
      day[:slots] = Event.available_slots(day[:date])
    end
    weekdays
  end

  def self.get_week(start_date)
    week = []
    (0..6).each do |n|
      day = {}
      day[:date] = (start_date + n.days).strftime('%Y/%m/%d')
      week << day
    end
    week
  end

  def self.openings(day)
    open = Event.where(kind: 'opening').select do |ev|
      ev.starts_at.to_date == day.to_date ||
        ev.weekly_recurring == true && ev.starts_at.wday == DateTime.parse(day).wday
    end
    open.map do |ev|
      Event.new(starts_at: DateTime.parse((ev.starts_at + (DateTime.parse(day) - ev.starts_at.to_date).days).to_s), ends_at: DateTime.parse((ev.ends_at + (DateTime.parse(day) - ev.ends_at.to_date).days).to_s))
    end
  end

  def self.appointments(day)
    Event.where(kind: 'appointment').select do |ev|
      ev.starts_at.to_date == day.to_date
    end
  end

  def self.available_slots(day)
    slots = []
    if Event.appointments(day) == []
      Event.openings(day).each do |op|
        slots << Event.slot_to_string(op.starts_at)
        (1..(Event.minutes(op) / 30 - 1)).each do |n|
          slots << Event.slot_to_string(op.starts_at + n * 30.minutes)
        end
      end
    else
      Event.openings(day).each do |op|
        slot_start = op.starts_at
        slot_end = op.starts_at + 30.minutes
        slots << Event.slot_to_string(op.starts_at) if Event.slot_available?(slot_start, slot_end, day) == true
        for n in 1..((Event.minutes(op) / 30) - 1) do
          slot_start = op.starts_at + n * 30.minutes
          slot_end = slot_start + 30.minutes
          slots << Event.slot_to_string(slot_start) if Event.slot_available?(slot_start, slot_end, day) == true
        end
      end
    end
    slots
  end

  def self.minutes(event)
    (event.ends_at - event.starts_at) / 60
  end

  def self.slot_available?(slot_start, slot_end, day)
    Event.appointments(day).none? do |app|
      slot_start < app.ends_at && slot_end > app.starts_at
    end
  end

  def self.slot_to_string(datetime)
    datetime.strftime('%-l:%M')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def check; end

  def availabilities
    @day = DateTime.parse(params[:day])
    @availabilities = Event.availabilities(@day)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_form.html.erb
<div class="search-bar-index mt-3 d-flex justify-content-center" >
    <%= form_tag availabilities_path, method: :get do %>
      <span class="input" style="position: relative;left: 15px;">
        <%= date_field_tag :day, params[:day], class: "form-control d-inline w-auto border-radius-search", placeholder: "start day"  %>
      </span>
      <span class="input" style="position: relative;left: -5px; bottom: 1px;"><%= submit_tag "Search", class: "btn btn-primary border-radius-search-btn" %>
      </span>
    <% end %>
</div>

app/views/events/availabilities.html.erb
<div class="container">
  <h1>Availabilities for <%= @day.strftime("%Y/%m/%d") %></h1>
  <% @availabilities.each do |day| %>
    <h4> Day: <%= day[:date] %>  </h4>
    <h4> Slots: <%= day[:slots] %>  </h4>
  <% end %>
</div>

app/views/events/check.html.erb
<div class="container mt-3">
  <h1>Please choose a day to start looking for when the doctor is available</h1>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctolibTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>